### ISSUE TITLE
ReadMe를 따라 실행하면 에러가 납니다.

### ISSUE THREAD

**Issue by blackCmd** [AI-GrandChallenge/round-1#11]
How to run의 설명대로 `nsml run -d tr-1 -e main.py -c 2 --memory 16G` 이 명령어를 그대로 복붙하면 아래와 같이 에러가 납니다.

> 
![image](https://user-images.githubusercontent.com/13531174/88518539-9d553680-d02b-11ea-9862-20eed8caf43b.png)

어떻게 실행시키나요? 혹시 로컬에도 이 깃허브의 파일들을 다운받아놔야하나요?

**Comment by bluebrush** [comment]
@blackCmd 님, #12 참고하시어, CLI 받으시고, login 상태에서 진행부탁드립니다.

**Comment by blackCmd** [comment]
> @blackCmd 님, #12 참고하시어, CLI 받으시고, login 상태에서 진행부탁드립니다.

실수로 본문에 에러내용을 기재하지못했습니다. 본문 수정했습니다.
이미 로그인 된 상태입니다.
본문과 같이 `nsml run -d tr-1 -e main.py -c 2 --memory 16G`를 입력하면 `Error:unknown argument(s)`라는 오류가 뜨는데 어떤 인자가 잘못됐나요?

**Comment by blackCmd** [comment]
> @blackCmd 님, #12 참고하시어, CLI 받으시고, login 상태에서 진행부탁드립니다.

엇.. 갑자기 됩니다. 감사합니다.
