### ISSUE TITLE
[track-2] model weight 호출 문제

### ISSUE THREAD

**Issue by symoon94** [AI-GrandChallenge/round-1#119]
저희 weight 불러와서 테스트 중인데 제대로 불러와서 테스트가 이루어지고 있는지 확인하고 싶어 이슈 올립니다.

utils에 있는 inference()에서 직접 weight를 load하고 그 모델로 inference 진행하여 얻은 결과값을 리턴하고 있습니다.

submit -t 모드로 실행시켜보면 모델이 잘 로드되고 inference 결과도 잘 나오는데 실제 submit시 결과가 Score가 0.31297709923664224 계속 동일하게 나옵니다. 전에 보니 처음에 여러 팀들이 모두 동일한 스코어로 0.31297709923664224 나오는 것을 본 적이 있어 혹시 샘플코드의 샘플 weight나 모델이 작동하고 있는 것인지 의문이 듭니다. 혹시 확인가능할까요?

세션: t0048/tr-2/220

**Comment by nsml-admin** [comment]
세션 t0048/tr-2/220 의 제출된 결과의 output을 보니(infer에서 return된 값) 결과값의 갯수가 비정상적으로 적게 나왔습니다, 그것과 관련이 있을것 같습니다.

**Comment by symoon94** [comment]
> 세션 t0048/tr-2/220 의 제출된 결과의 output을 보니(infer에서 return된 값) 결과값의 갯수가 비정상적으로 적게 나왔습니다, 그것과 관련이 있을것 같습니다.

답변감사합니다. 비정상적으로 적게 나왔다는 뜻은 모든 음원파일에 대해 결과값을 못냈다는 뜻이 맞나요?

**Comment by nsml-admin** [comment]
네 맞습니다

**Comment by symoon94** [comment]
> 네 맞습니다


```
def inference(model, test_path: str) -> pd.DataFrame:     
    DIR_PATH = f'{test_path}/'
    DIR_PATH = DIR_PATH
    AUDIO_PATH = os.path.join(DIR_PATH, "test_data")
    wav_list = glob.glob(AUDIO_PATH+"/*.wav")
```

파일 경로  {test_path}/test_data 디렉토리 안에 모든 음원 파일이 있는 것이 맞지요? 테스트 할때는 아무런 에러가 뜨지 않는데 혹시
 t0048/tr-2/304 test4
의 에러메세지를 알 수 있을까요?
