### ISSUE TITLE
[트랙 3] 에러 문의

### ISSUE THREAD

**Issue by haewonChun** [AI-GrandChallenge/round-1#126]
아래와 같은 오류가 뜹니다.
이유를 알 수 있을까요?

t0042/tr-3/177/pascal 입니다.

![KakaoTalk_20200730_215348525](https://user-images.githubusercontent.com/38089995/88926767-698b4280-d2b1-11ea-892a-a8b90ac21fe2.png)

**Comment by bluebrush** [comment]
@theSeventhHeaven 님, submit과정 중 infer 시간이 1시간(3600sec)이 넘어서 강제 종료되면서 나온 메시지로 보여집니다. infer의 속도 개선이 필요한 것으로 예상됩니다.
