### ISSUE TITLE
[tr-1] 제출 시 다음과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by G-Bong** [AI-GrandChallenge/round-1#131]
안녕하십니까.

테스트 모드로 제출 시에는 정상적으로 output file이 생성되고 세션이 종료되었습니다.
그런데 제출모드로 하면 다음과 같은 에러가 발생합니다.
>.Error occurred while inference. You can check error 'nsml submit --test'
IndexError: index 2 is out of bounds for dimension 0 with size 2
Infer test set takes 2676.482486009598 seconds
..Error: Fail to get prediction result: t0080/tr-1/236/model
FATA[2020/07/31 01:57:37.496] Internal server error          

빠른 확인 부탁드립니다.

**Comment by bluebrush** [comment]
@G-Bong 님, 안녕하세요. 아래와 같이 오류코드가 확인됩니다. 도움이 되실까요?
```
  File "nsml_submit.py", line 204, in infer
    return _infer(model, root_path)
  File "nsml_submit.py", line 129, in _infer
    new_framed_metas[batch_iter, num] = each_row[batch_iter]
IndexError: index 2 is out of bounds for dimension 0 with size 2
```
