### ISSUE TITLE
그래픽카드 관련 질문입니다.

### ISSUE THREAD

**Issue by hi-one-gg** [AI-GrandChallenge/round-1#134]
이번 대회 관련된 nsml 홈페이지에보면
그래픽카드 0과 1이 있는데
그래픽카드 1이 있는 가로행에 보면 cpu가 8로 돼있습니다. 
그렇다는 말은 그래픽카드1을 쓰는 사람은 cpu를 8개를 쓰는건가요?

**Comment by bluebrush** [comment]
안녕하세요. 
이번 대회에서 권장 리소스 사용은 
nsml run -d dataset -g 1 -c 4  입니다. 
1gpu 에 4 cpu입니다. 
위에 문의하신 화면은 사용중이라는 말은 아니며, 최대 할당 가능입니다.

**Comment by blackCmd** [comment]
> 안녕하세요.
> 이번 대회에서 권장 리소스 사용은
> nsml run -d dataset -g 1 -c 4 입니다.
> 1gpu 에 4 cpu입니다.
> 위에 문의하신 화면은 사용중이라는 말은 아니며, 최대 할당 가능입니다.

nsml run -d dataset -g 1 -c 8로 했더니 할당이 안되더라구요.. 7도 안되고 그러던데 
한번에 -c 8은 안되는건가요?

**Comment by hi-one-gg** [comment]
> 안녕하세요.
> 이번 대회에서 권장 리소스 사용은
> nsml run -d dataset -g 1 -c 4 입니다.
> 1gpu 에 4 cpu입니다.
> 위에 문의하신 화면은 사용중이라는 말은 아니며, 최대 할당 가능입니다.

아 혹시 그렇다면 -g 2옵션을 사용한다면 한번에 2개가 다 사용가능하단건가요?

**Comment by bluebrush** [comment]
아니요.
 -g 2 사용하시면 안됩니다.  1개 GPU에서 작업이 끝나야하며, -g 2 사용확인시 쿼터 축소하도록 하겠습니다.

**Comment by hi-one-gg** [comment]
> 아니요.
> -g 2 사용하시면 안됩니다. 1개 GPU에서 작업이 끝나야하며, -g 2 사용확인시 쿼터 축소하도록 하겠습니다.

네 철저하게 모니터링해주셔서 축소시켜주시기 바랍니다.
