### ISSUE TITLE
프로젝트폴더 업로드와 서버에 모듈설치는 어떻게 해야합니까?

### ISSUE THREAD

**Issue by blackCmd** [AI-GrandChallenge/round-1#16]
먼저 NSML을 처음 접하고 자세한 설명을 듣지못해 NSML이 매우 낯설고 사용방법을 모르겠습니다.

1. 저는 여러 파일들과 모듈이 담긴 프로젝트 폴더를 통째로 NSML 서버에 올려서 거기서 제 모델을 동작시키려고 하는데 이럴 땐 어떻게 해야합니까? 프로젝트 폴더 이름은 folder이고 해당 폴더 안에서 실행할 파일이름은 gogo.py라고 가정해주십시오

2. 저희는 cython, numba, opencv와 같이 여러 써드파티 모듈과 오픈소스들을 사용하고 있는데 이런 다양한 모듈들은 어떻게 서버에서 설치하나요?

**Comment by DeepLearningHB** [comment]
덧붙여서, 모델 2개를 동시에 돌려야 추론이 가능한데 하나는 pytorch 하나는 tensorflow2 입니다.. 가이드라인 제시 부탁드립니다...

**Comment by junsukchoe** [comment]
안녕하세요.

1. `folder` 디렉토리 안에서 `nsml run` 커맨드를 실행하시면 해당 디렉토리에 있는 모든 파일들이 NSML로 업로드 된 후, `main.py`가 실행됩니다. 만약 실행파일 이름이 `main.py`가 아닐 경우 `-e`옵션으로 엔트리파일 이름을 지정할 수 있습니다. 예시: `nsml run -e gogo.py`

2. 원하시는 패키지들이 설치되어 있는 도커 이미지를 만드신 후 활용하시면 됩니다.

**Comment by junsukchoe** [comment]
다음 이슈도 참조 부탁드립니다: #12

**Comment by blackCmd** [comment]
> 안녕하세요.
> 
> 1. `folder` 디렉토리 안에서 `nsml run` 커맨드를 실행하시면 해당 디렉토리에 있는 모든 파일들이 NSML로 업로드 된 후, `main.py`가 실행됩니다. 만약 실행파일 이름이 `main.py`가 아닐 경우 `-e`옵션으로 엔트리파일 이름을 지정할 수 있습니다. 예시: `nsml run -e gogo.py`
> 2. 원하시는 패키지들이 설치되어 있는 도커 이미지를 만드신 후 활용하시면 됩니다. 좀 더 자세한 내용은 다음 이슈에 대한 답변 참조 부탁드립니다: [#32 (comment)](https://github.com/AI-GrandChallenge/round-1/issues/32#issuecomment-664391603)

와...... 1번에 대한 답변 정말 찾았던건데 너무 감사합니다 ㅠㅠ!
