### ISSUE TITLE
세션 강제로 죽일 수 없나요 ??

### ISSUE THREAD

**Issue by pyw2429** [AI-GrandChallenge/round-1#19]
Name          Created          Args    Status     Summary    Description    # of Models    Size    Type
------------  ---------------  ------  ---------  ---------  -------------  -------------  ------  ------
t0039/tr-1/3  Not created yet          Allocated                            0              0       normal
t0039/tr-1/2  Not created yet          Allocated                            0              0       normal

위에처럼 세션이 잡혀있어서 죽지도 않고 nsml stop도 안먹고 웹에서도 못죽이고 gpu잡고 있어서 돌리지도 못하내요 ...
수동으로 요청을 계속 드려야 하는건지...

**Comment by blackCmd** [comment]
어떻게 죽이나요 ? 질문을 닫으셨네요

**Comment by nsml-admin** [comment]
`nsml rm -f [session]`으로 종료시킬수 있습니다.
