### ISSUE TITLE
세션의 파일 크기 제한

### ISSUE THREAD

**Issue by caffeinism** [AI-GrandChallenge/round-1#20]
현재 파일 100개, 총 300MB 제한으로 걸려있는데 제한을 조금 늘려주실 수 없나요?

**Comment by nuualab** [comment]
지금 저희는 다수의 모델을 앙상블해서 사용하는데 300MB는 올릴수도 없는 용량 입니다.
1GB 수준은 되어야 할 것 같습니다.

**Comment by caffeinism** [comment]
#47
