### ISSUE TITLE
Custom Docker image 업로드 어디에서 하는 건가요?

### ISSUE THREAD

**Issue by mckim527** [AI-GrandChallenge/round-1#21]
<h3>고생이 많으십니다.</h4>

Custom Docker image 업로드 어디에서 하는 건가요?

**Comment by lifefeel** [comment]
저도 이게 가능한지 궁금합니다. 매번 이미지 새로 만들어지는 시간이 너무 기네요..

**Comment by bluebrush** [comment]
docker hub에 하시면 됩니다.
