### ISSUE TITLE
Pytorch 컨테이너 이미지 Release 버전 문의

### ISSUE THREAD

**Issue by tk22lee** [AI-GrandChallenge/round-1#24]
안녕하세요

컨테이너 이미지의 Pytorch 버전이 stable 버전이 아닌 1.6.0 알파버전으로 보입니다.

그리고 해당 버전이 네트워크 코드에 변화가 있는 버전이라 이전버전에서 만든 특정 모델은 돌아가지 않습니다.

사용자들이 가장 많이 사용할 stable버전인 1.5.1 으로 버전을 낮추어야 할것으로 생각됩니다.

감사합니다

**Comment by 2KangHo** [comment]
0.3.0인 것 같습니다

**Comment by tk22lee** [comment]
torchvision 버전을 말씀하신 것이지요?

**Comment by tk22lee** [comment]
https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/session/prepare_a_session_environment.html

아래 이슈를 참고하면 여기 설명대로 원하는 컨테이너 이미지를 바꾸어야 하는것 같이 보이긴합니다..

**Comment by tk22lee** [comment]
https://ai.nsml.navercorp.com/support

여기에서 지원가능한 항목 확인했습니다.

이슈 닫겠습니다
