### ISSUE TITLE
Track 2 데이터셋 관련

### ISSUE THREAD

**Issue by mystlee** [AI-GrandChallenge/round-1#26]
Track 2 코드 질문이 있습니다.
주어진 data_loader.py에서 load_audio 함수를 보면, short format으로 읽게 되어있습니다.
해당 코드처럼 파일을 읽는 구조는 mono 형태의 음원을 read하는건데,
문제정의서에는 stereo로 정의되어 있습니다.
test data가 확실히 stereo인지 확인 가능할까요?

**Comment by hwany-j** [comment]
안녕하세요. 해당 코드에서는 mono 형태로 음원을 읽었지만, 음원 파일은 stereo type입니다. 
문제정의서와 같이 stereo 타입의 16k 40초짜리 음원입니다. 
아래 코드와 결과 첨부합니다. 
<img width="656" alt="스크린샷 2020-07-27 오후 10 16 50" src="https://user-images.githubusercontent.com/57430984/88546275-1918a880-d057-11ea-9ebf-29b4a19f2758.png">

**Comment by mystlee** [comment]
빠른 답변 감사합니다~
