### ISSUE TITLE
[TRACK 1] 데이터 구조가 궁금합니다.

### ISSUE THREAD

**Issue by SJP8530** [AI-GrandChallenge/round-1#36]
README.md의 설명을 읽어봐도 어떻게 해야 할지 잘 모르겠습니다.

1. 애초에 트랙 1은 이미지에서 쓰러진 사람을 검출하는 문제가 아니라, 동영상에서 쓰러지는 사람을 검출하는 문제로 알고 있었습니다. 그런데 설명된 Dataset Description을 보면 마치 모든 image들이 영상분류 없이 test_data라는 한 폴더 내에 뭉텅이로 들어 있는 것처럼 보입니다. 제가 해석한 것이 맞나요? 

2. 350 frame * 300 영상 = 105000개의 이미지가 한 폴더 내에 들어 있는 것이 맞다면, data loader가 350 프레임씩 불러오면서 영상 별로 분류되게 되어 있는지요? 애초의 영상분석이라는 track 1의 주제를 보면 data_loader가 영상별로 이미지를 350개의 배치씩 load해줘야 한다고 생각합니다. data_loader가 어떤 배치 사이즈로 몇 개의 이미지씩 load되는지, 영상 별로 350개씩 load되는지, 아니면 단순히 고정된 이미지 개수만큼 랜덤하게 뽑아오는지 알지 못해 구현하기가 힘듭니다. dataset의 구조와 함께 data_loader.py 가 어떤 형태로 이미지를 불러오는지 공개해주실 수 있나요?

**Comment by blackCmd** [comment]
이거 진짜 좋은 질문이네요 알려주시기 바랍니다.
