### ISSUE TITLE
[Track4] 압축 관련 룰 문의

### ISSUE THREAD

**Issue by kjy12345** [AI-GrandChallenge/round-1#4]
안녕하세요.
이번에 새롭게 정해진 룰 중에 아래와 같은 룰이 있는데요.

"Submit시 압축상태로 되어 있다가 모델 Run시 압축이 해제되는 방식의 방법은 불허함"

여기서 "압축상태"에 대해 의미가 모호하여 문의드리고자 합니다.
저기서 "압축상태"가 무엇을 말하는 것인지요?

예를 들어, zip이나 tar, numpy의 npz와 같은 lossless 파일 압축 기능으로 압축된 것을 의미하나요?
아니면, 그 외에 sparse matrix format으로 저장했다가, 모델 run시에 dense 버전으로 바꿔서 모델에 로드하는 경우도 포함하는 것인가요?

후자라면, 사용하는 딥러닝 프레임워크(e.g., Torch, TF)에서 직접적으로 지원하지 않는 weight 저장 형식을 사용하는
모든 경우가 해당되는 것 같은데, 이에 대해 구체적인 설명 부탁드립니다.

**Comment by JeiKeiLim** [comment]
zip 같은 압축 포맷은 불가한다고 문서에 나와있더라구요.

**Comment by kjy12345** [comment]
저 룰만 봐서는 zip 만을 이야기하는지, 아니면 sparse matrix 같은 경우도 포함하는지 모호해서 문의드렸습니다. ㅎㅎ

**Comment by JeiKeiLim** [comment]
> 저 룰만 봐서는 zip 만을 이야기하는지, 아니면 sparse matrix 같은 경우도 포함하는지 모호해서 문의드렸습니다. ㅎㅎ

저도 그 부분은 조금 모호하다고 생각중이긴 한데 공식 답변이 있으면 좋긴 하겠네요 ㅎㅎ
NSML 이라도 열려야 되는지 테스트를 해볼텐데요

**Comment by 2KangHo** [comment]
저희도 그 부분이 애매해서 huffman coding 등으로 저장해서 load할 때 바뀌는 게 가능한지 금요일 밤에 공지 올라오고 거의 바로 메일로 문의를 보냈는데 아직 답장이 없네요.. ㅎㅎㅎ,,

**Comment by kjy12345** [comment]
Huffman coding이 허용 되면 zip도 안될 이유가 없긴 한데.. 명확한 기준이 필요해보이네요.

**Comment by 2KangHo** [comment]
그래서 지금은 그냥 CSR이나 huffman coding으로 저장하고 load할때 푸는 것도 다 압축이라고 생각이 들어서 배제하고 생각 중인데 잘 모르겠네요,,

**Comment by 2KangHo** [comment]
https://github.com/AI-GrandChallenge/round-1/blob/f3c9dff78e1d642c052bafa3731e3bcb217517b7/iitp_category/main.py#L91

이렇게 되면 quantization은 사용해도 무용지물인데,., 정확한 기준을 빨리 알려줬으면 하네요,,

**Comment by kjy12345** [comment]
설마 그냥 logging 코드이지 않을까요... 심지어 {total_param} tensors 라고 하면 메세지도 잘못된거고요..

**Comment by 2KangHo** [comment]
@kjy12345 그렇게 생각은 합니다만 담당자님이 말이 없어서요,,, 답변을 달아주셔야 뭔가 올바른 방향으로 진행을 할텐데요,,
