### ISSUE TITLE
[트랙4] 문제 정의서에 Class Index Code가 잘못 됐습니다. 정정 요청 드립니다.

### ISSUE THREAD

**Issue by JeiKeiLim** [AI-GrandChallenge/round-1#41]
문서에는 Class Index Code 가 01로 시작하는데 실제 nsml test 로는 0 부터 시작하는 것으로 확인이 됩니다.
뿐만 아니라, csv 파일 작성 예시에는 Index code 가 한 자리수 인 경우에는 leading zero 가 들어갑니다.
이런 문서에는 정확한 내용이 들어가야하는데 이것 역시 확인 부탁 드리겠습니다.
아래 테이블에 정리 해놨습니다. 어떤 내용이 맞는지 확인 해주시면 감사하겠습니다.

|Class|문서상Index|코드상Index|
|-----|-----|-----|
|스니커즈슬립온|01|0|
|여성부츠워커|02|1|
|여성가방|03|2|
|힐펌프스|04|3|
|캐쥬얼가방|05|4|
|남성캐주얼화|06|5|
|패션모자|07|6|
|운동화|08|7|
|실내화슬리퍼|09|8|
|여성단화|10|9|
|아쿠아슈즈쪼리|11|10|
|여성샌들|12|11|
|아동책가방|13|12|
|아동모자|14|13|
|기타지갑|15|14|
|아동구두|16|15|
|남성정장화|17|16|
|남성워커부츠|18|17|
|기능화|19|18|
|아동운동화|20|19|
|아동외출여행가방|21|20|
|선글라스|22|21|
|아동샌들|23|22|
|남성가방|24|23|
|패션시계|25|24|
|남성지갑|26|25|
|기타시계|27|26|
|운동용가방|28|27|
|에어쿠션팩트|29|28|
|에센스앰플|30|29|
|클렌징필링|31|30|
|우산양산|32|31|
|여성지갑|33|32|
|안경테|34|33|
|베이스메이크업|35|34|
|여행용가방|36|35|
|팩마스크|37|36|
|스킨로션|38|37|
|향수|39|38|
|립케어블러셔|40|39|
|선케어|41|40|

**Comment by hwany-j** [comment]
네 맞습니다. 코드상 index가 맞습니다. 혼란을 드려 죄송합니다.

**Comment by JeiKeiLim** [comment]
네 알겠습니다~ close 하도록 하겠습니다!
