### ISSUE TITLE
[트랙3] 업로드 용량 문의

### ISSUE THREAD

**Issue by withcat-net** [AI-GrandChallenge/round-1#47]
저희 모델 파일 (.pth)이 300MB를 넘는데 300MB 이상 파일은 업로드 불가한 것이 대회 규칙인가요?
nsml 상에서 300MB 이상 파일 업로드를 막아놨네요.

**Comment by bluebrush** [comment]
@withcat-net 님, 현재, 동시 upload시 네트웍 및 storage 한계로 제한되어 있습니다. 혹시, 어느정도 크기일지 알수있을까요?
참고로, session 내부에서 wget 같은 tool으로 외부에서 downlaod하실 수 있으니 참고부탁드립니다.

**Comment by JunHyungKang** [comment]
@bluebrush 저같은 경우에는 약 1.5~2G정도 되는 모델인데요. 대회 기간중에 300M 업로드 제한을 풀 계획은 그럼 없는 것인가요?
그리고 script로 다시 외부에서 download해서 학습진행하는 경우에는 대회 rule에는 제한되는 내용은 없는 것으로 이해하면 될까요?

**Comment by bluebrush** [comment]
네에, 외부에서 download 받으셔도 됩니다. nsml run 실행시 session생성후, 내부 code에서 받으시면 될 것 같습니다. 
CLI에서 만약 2G로 정한다면, 100여명에 한시간마다 2GB씩 upload하시는 상황까지 가정해서해서 물리적인 한계가 있습니다.
