### ISSUE TITLE
[NSML] session 종료가 되지 않는 문제

### ISSUE THREAD

**Issue by caffeinism** [AI-GrandChallenge/round-1#51]
모델을 제출했는데 다음과 같은 로그가 나오고 끝났습니다.
```time="2020/07/28 07:00:44.227" level=fatal msg="run failed: rpc error: code = Unavailable desc = transport is closing"```
시간초과를 냈던 것 같은데 중요한건 그 이후에 해당 세션이 running 상태에서 종료가 되지 않습니다. (cli에서 rm, gui에서 rm 등 다 먹히지 않음)

어떻게 해결해야할까요?

**Comment by nsml-admin** [comment]
`nsml rm -f [session]`으로 해보실래요?

그래도안되면 세션네임을 알려주시기 바랍니다.

**Comment by caffeinism** [comment]
> `nsml rm -f [session]`으로 해보실래요?
> 
> 그래도안되면 세션네임을 알려주시기 바랍니다.

force 옵션을 주니까 잘 종료가 되네요. 감사합니다.
