### ISSUE TITLE
[트랙3] 예제 코드 실행 시 에러

### ISSUE THREAD

**Issue by withcat-net** [AI-GrandChallenge/round-1#55]
트랙3 예제 코드 실행시 다음과 같은 에러가 납니다.
import torch
from torch._C import *
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

어떤게 문제인건가요?

**Comment by nsml-admin** [comment]
gpu가 없는 환경에서 코드가 실행될때 발생하는 문제입니다.

`nsml run`을 할때  `-g1`  옵션추가해서 해보실래요?

**Comment by withcat-net** [comment]
@nsml-admin 답변 감사합니다.
1. -g1 인가요? -g 1 인가요? 띄어쓰기 차이입니다.
2. setup.py에 mmcv-full 이라는 모듈을 설치하라고 했는데요, 이 모듈을 설치할 때도 동일한 에러가 납니다.

**Comment by nsml-admin** [comment]
1. `-g 1` 입니다. (띄어쓰기)
2. 에러가 발생한 세션네임들을 알려주시기 바랍니다.

**Comment by withcat-net** [comment]
에러 메시지는 다음과 같습니다. 세션을 빌드할 때 문제가 생겨서 https://ai.nsml.navercorp.com/terminal 여기서도 뜨지 않습니다.

t0086/tr-3/21: Fail to build session
Warning: t0086/tr-3/21 is already removed. It will be removed from nsml soon
[]
Done
Error: Fail to build docker image. Please Contact Dev team
FATA[2020/07/28 17:03:31.961] Internal server error

**Comment by nsml-admin** [comment]
해당에러가 발생했던 세션에서 사용한 setup.py를 보여주실수 있나요?

**Comment by withcat-net** [comment]
@nsml-admin 
아래와 같습니다.

#nsml: nsml/default_ml:cuda9_torch1.0
from distutils.core import setup

setup(
    name='iitp_trash',
    version='1.0',
    install_requires=[
        'tqdm',
        'pillow',
        'addict',
        'yapf',
        'mmcv-full',
        'gitpython',
    ]
)

**Comment by nsml-admin** [comment]
도커환경을 torch 최신버전에서 실행해보니깐 됩니다.

https://ai.nsml.navercorp.com/support 에서 도커이미지들을 확인하실수 있는데요,

도커이미지를 nvcr.io/nvidia/pytorch:20.03-py3 로 바꿔주시던가 새로 빌드를 해서 그 이미지를 사용하면 될거같습니다.

**Comment by withcat-net** [comment]
도커이미지 란게 있었군요.
감사합니다.
