### ISSUE TITLE
nsml 테스트 코드 서브밋 이후

### ISSUE THREAD

**Issue by wildcat842** [AI-GrandChallenge/round-1#58]
생소한 NSML을 쓰려니 너무 어렵네요.  track3 번의 t9999 팀 사용자 nobody 라고 가정해주세요. 
==========================================
주어진  테스트 코드를 이용하여 다음과 같이 submit 까지 실행하다가 

t9999 submit t9999/tr-3/1  checkpoint

화면이 멈추어서 엔터를 누른 상태에서 다음과 같은 submit session 이 있는 것을 확인하였습니다. 
==========================================
~nobody$  nsml ps -d tr-3
Name          Created         Args                   Status    Summary    Description             # of Models    Size      Type
------------  --------------  ---------------------  --------  ---------  ----------------------  -------------  --------  ------
t9999/tr-3/3  41 minutes ago  --mode test --pause 1  Running              submit of t9999/tr-3/1  1              42.71 MB  submit
t9999/tr-3/2  an hour ago     --mode test --pause 1  Running              submit of t9999/tr-3/1  1              42.71 MB  submit

==========================================
tr-3/1 의 코드를 업로드한 새로운 세션이 실행되는 상태인데, 이 세션에 대해서 
~nobody$ nsml model ls  t9999/tr-3/3

Usage: nsml model ls [OPTIONS] SESSION

Error: Invalid value for "SESSION": Cannot ls [t0128/tr-3/3] (Only nsml rm is valid for submit sessions)
FATA[2020/07/28 15:34:47.158] Internal server error                        

==========================================
리더보드에 있는 세션 정보는 비슷합니다.

NSML Log start!
Usage: nsml logs [OPTIONS] SESSION

Error: Invalid value for "SESSION": Cannot logs [t9999/tr-3/3] (Only nsml rm is valid for submit sessions)
==========================================
이미 러닝된 세션은 어떻게 종료하는지
그리고 submit 취소하고 새롭게 nsml run 은 가능한 것인지요?

**Comment by nsml-admin** [comment]
이미 러닝된 세션은 `nsml rm -f` 로 삭제 가능합니다.
쿼터가 충분하다면, submit취소하고 새롭게 `nsml run`도 가능합니다.

**Comment by wildcat842** [comment]
빠른 응답 감사합니다. ^^
