### ISSUE TITLE
[트랙3] nsml 환경 문의

### ISSUE THREAD

**Issue by withcat-net** [AI-GrandChallenge/round-1#59]
저희가 모델 구동을 위해 사용하고 있는 라이브러리의 경우 파일 개수가 100개가 넘어가서 아예 서버에 올라가지가 않습니다.

main.py를 run 했을 때 다음과 같은 에러가 나옵니다.
FATA[2020/07/28 15:28:12.445] total number of files cannot exceed 100

또 모델 구동을 위해 라이브러리 내부에서 setup.py를 돌려서 빌드를 해야하는데, 이 부분은 어떻게 nsml 안에서 구현을 할 수 있을까요?

**Comment by bluebrush** [comment]
@withcat-net 님, 사용에 불편을 드려서 죄송합니다. CLI의 file 파일개수/사이즈 제한은 시스템 안정성을 변경이 어려운 상황입니다. 
혹시, tar 같은 것으로 묶어서 runtime에 푸시는 방안은 도움이 되실지 조심스럽게 의견드립니다.

**Comment by withcat-net** [comment]
그렇게 한 번 해보겠습니다.
