### ISSUE TITLE
[NSML] submit관련 질문

### ISSUE THREAD

**Issue by caffeinism** [AI-GrandChallenge/round-1#60]
1. score는 nsml submit 명령어를 친 그 터미널에서 대기하고 있다가 보는 방법밖에 없나요?

2. 동일한 코드 두 번을 submit했는데 한번은 제대로 제출 되고 한번은 서버에서 hang중인데 혹시 이런 경우에 어떤 문제가 있는건지 알 수 있을까요?

**Comment by nsml-admin** [comment]
1. 네 맞습니다.
2. 동일한 코드인데 모델이 다르면 submit시간이 다를수도 있습니다. 사용하신 명령어와 세션을 알려주시면 로그를 확인해보겠습니다.

그외에 완전히 동일한 코드와 동일한 모델을 서브밋을 했다면 비슷한 시간에 submit이 완료되는게 정상입니다.

**Comment by JuYong-Shin** [comment]
트랙 4인데, 리더보드를 초기화한다는 메세지를 본 후 submit을 했었습니다. 잠깐 다른일을 하고 왔더니 리더보드에서 사라졌습니다. 그래서 아까 submit한 것을 그대로 다시 submit 했습니다. 그런데 점수가 바뀌었고, 다시  리더보드에 기록이 되었습니다. 
(1) 기록이 사라진 이유
(2) 점수가 바뀐 이유
(3) submit가 제대로 되고 있는지, 아니면 이상하게 되고 있는지 확인할수 있나요?
(4) submit할 때 train mode에서   epoch는 0으로 세팅해야 하나요?
