### ISSUE TITLE
NSML RUN 할 때 에러납니다.

### ISSUE THREAD

**Issue by blackCmd** [AI-GrandChallenge/round-1#63]
이미지를 봐주세요.

> ![image](https://user-images.githubusercontent.com/13531174/88638068-f4bfd900-d0f5-11ea-98d4-29e239ec1d95.png)

**Comment by nsml-admin** [comment]
setup.py 또는 requirements.txt가 뭔가 문법에 안맞아서 발생한 문제같습니다.

혹시 로컬에서 
1. setup.py 를 쓰는 경우
`(setup.py와 현재 디렉토리가 같다는 가정하에) pip install .`  또는

2. requirements.txt를 쓰는경우
`pip install -r requirements.txt` 가 제대로 동작하는지 확인해주시기 바랍니다.

위방법으로 로컬에서 제대로 되는데 nsml에서 안되는거라면 setup.py를 알려주시면 테스트해보겠습니다.

**Comment by blackCmd** [comment]
> setup.py 또는 requirements.txt가 뭔가 문법에 안맞아서 발생한 문제같습니다.
> 
> 혹시 로컬에서
> 
> 1. setup.py 를 쓰는 경우
>    `(setup.py와 현재 디렉토리가 같다는 가정하에) pip install .`  또는
> 2. requirements.txt를 쓰는경우
>    `pip install -r requirements.txt` 가 제대로 동작하는지 확인해주시기 바랍니다.
> 
> 위방법으로 로컬에서 제대로 되는데 nsml에서 안되는거라면 setup.py를 알려주시면 테스트해보겠습니다.

현재 레포의 코드를 다시 다운받아 실행해봤더니 세션이 잘 만들어졌습니다.
감사합니다.
