### ISSUE TITLE
TR-3 : 도커이미지 없이 setup.py 에서  install_requires 로 처리가능한 라이브러리

### ISSUE THREAD

**Issue by wildcat842** [AI-GrandChallenge/round-1#65]
팀 이름은 t9999, 이름 nobody 라고 가정합니다. 

main.py 에 사용하고자 하는 라이브러리를 import 를 하려고 합니다. 

main.py 에 해당 하는 몇가지 라이브러리 import 를 추가하고, 
아래와 같이 setup.py 의 inlstall_requires 에 지정을 해주면
=======================================================
#nsml: nsml/default_ml:cuda9_torch1.0
from distutils.core import setup

setup(
    name='iitp_trash',
    version='1.0',
    install_requires=[
                      'tqdm',
                      'pillow',
                      'fastai',
                      'matplotlib',
                      'datetime'
                      ]
)

=======================================================
PIL, re 등은 distribution 에러가 납니다만, fastai, matplotlib, datetime 은 오류가 나지는 않네요. 

1) 이 경우 도커 이미지 없이 이러한 라이브러리 import 가 가능합니까?
2) 그리고 이런 경우 nsml run 을 해도 세션은 생성되지만 check point 가 생성되지 않습니다. 

=======================================================
......
Building docker image. It may take a while
.........
Session t9999/tr-3/19 is started

nobody@: iitp_trash$ nsml model ls t9999/tr-3/19
Checkpoint    Last Modified    Elapsed    Summary    Size
------------  ---------------  ---------  ---------  ------

**Comment by nsml-admin** [comment]
안녕하세요.

1. 도커이미지 없이 저러한 라이브러리 import는 불가능합니다. NSML에서 지원하는 도커 이미지는 [여기에](https://ai.nsml.navercorp.com/support) 있는데요, 이러한 도커환경에서 해보시다가 안되면 에러 메세지와 세션이름을 알려주면 확인해보겠습니다.

2. check point생성은 `nsml.save()`함수를 통해서 만들수가 있는데요, baseline을 참조해보시기 바랍니다. https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_trash/main.py#L176

**Comment by wildcat842** [comment]
main 에서 추가하여 사용하는  라이브러리는 다음과 같습니다. 

from fastai import *
from fastai.vision import *
from fastai.metrics import error_rate
from pathlib import Path
from matplotlib import patches, patheffects
from datetime import datetime

--------------------------------------
알려주신 도커이미지 사용하였고요, 
#nsml: nvcr.io/nvidia/pytorch:20.03-py3
from distutils.core import setup

setup(
    name='iitp_trash',
    version='1.0',
    install_requires=[
                      'tqdm',
                      'pillow',
	              'fastai',
                      'matplotlib',
	              'datetime' 
		      'pathlib'
                      ]
)

----------------------------------
오류는 다음과 같습니다. (체크포인트가 생기지 않아서, 여러번 재시도 끝에 가까스로 반가운 오류가 나왔군요.,

Building docker image. It may take a while
...Sending build context to Docker daemon  112.6kB
Step 1/11 : FROM nvcr.io/nvidia/pytorch:20.03-py3
 ---> 16c4987611fa
Step 2/11 : USER root
 ---> Using cache
 ---> a320fa8f0b91
Step 3/11 : WORKDIR /app
 ---> Using cache
 ---> a450924f7418
Step 4/11 : RUN (groupadd -r nsml || echo nsml group already exists) && (useradd --no-log-init -u 1002 -ms /bin/bash -r -g nsml nsml || echo nsml user already exists)
 ---> Using cache
 ---> 1dcfbdd5e6ab
Step 5/11 : RUN touch /var/log/nsml.log && chown nsml:nsml /var/log/nsml.log && mkdir -p /home /app &&chown nsml: /home /app &&mkdir /nsml_nfs_output && chown nsml:nsml /nsml_nfs_output
 ---> Using cache
 ---> da8690d5ce85
Step 6/11 : LABEL "ai.clova"="1"
 ---> Using cache
 ---> 176fa041ed51
Step 7/11 : RUN pip --no-cache-dir install redis==2.10.6 minio==5.0.6 dill==0.3.1.1 pymongo==3.10.1 simplejson==3.17.0 requests==2.22.0
 ---> Using cache
 ---> 679f628ac9e1
Step 8/11 : RUN echo H4sICH0/IF8AA3NldHVwLnB5AHWNzQqDMBCEz+YpAj2khTbaehN8klIk1YgL+XOzWnz7WrGXVueyMDPfzsFFawruxhol+NSN0IBKw0Qe6664ZTLLL2HKWYve8gYiDQQmytqj5mCDR+JR0xAYW86R8VlOWV0KAAoVoYqdOC/2qDGCd6W4ymy1wEVSxlSo+wFQx/K+2P8S1Dd2hTbSAMb415wnP0Gr5gHYB62iYDwZeG7AjSJNYLXgLEm+S4q6T3vn4YOd2BtubDKMVAEAAA== | base64 -d | gunzip - > /app/setup.py
 ---> Running in 23479ddc5c53
Removing intermediate container 23479ddc5c53
 ---> f9e9f83fd6fe
Step 9/11 : RUN cd /app; ([ ! -f setup.py ] || pip install .) && ([ ! -f requirements.txt ] || pip install -r requirements.txt)
 ---> Running in 5becb639544d
Processing /app
Requirement already satisfied: tqdm in /opt/conda/lib/python3.6/site-packages (from iitp-trash==1.0) (4.31.1)
Collecting pillow
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
Collecting fastai
  Downloading fastai-1.0.61-py3-none-any.whl (239 kB)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.6/site-packages (from iitp-trash==1.0) (3.2.1)
ERROR: Could not find a version that satisfies the requirement datetimepathlib (from iitp-trash==1.0) (from versions: none)
ERROR: No matching distribution found for datetimepathlib (from iitp-trash==1.0)

t0128/tr-3/66: Fail to build session
Warning: t0128/tr-3/66 is already removed. It will be removed from nsml soon
[]
Done
Error: Fail to build docker image. Please Contact Dev team
FATA[2020/07/29 00:08:55.825] Internal server error

**Comment by nsml-admin** [comment]
@wildcat842 setup.py에서 
'datetime' 와 'pathlib' 사이에 "," 가 빠진거 같습니다.
