### ISSUE TITLE
[NSML] inference 제한시간 1시간에 docker build 시간도 포함되어있나요?

### ISSUE THREAD

**Issue by caffeinism** [AI-GrandChallenge/round-1#68]
제출 딜레이 1시간은 제출 하자마자 시작되는 것 같은데 혹시 inference도 동일하게 submit 명령어를 치자마자 시작되나요?

**Comment by bluebrush** [comment]
@caffeinism 님, 아닙니다. model load가 끝난후 부터 1시간입니다.

**Comment by caffeinism** [comment]
감사합니다.
