### ISSUE TITLE
테스트 데이터 셋에 접근하려면 경로가 어떻게 되나요?

### ISSUE THREAD

**Issue by hi-one-gg** [AI-GrandChallenge/round-1#69]
트랙1 참가자입니다.
파이썬에서 `for (sub_root, dirs, files) in os.walk(root_dir):` 이런식으로 해서 모든 이미지들을 다 찾아가면서 인퍼런스 하려고 합니다. `main.py`를 기준으로 테스트 셋이 어디있는지 사대경로나 절대경로를 알려주세요.

main.py에 보면 아래와 같은 코드가 있습니다. 혹시 이 경로가 테스트셋의 절대 경로인가요? 
> `os.path.join('/home/data/iitp_2020_fallen_final/nsml_dataset/test/test_data')`

끝으로 주최측에서는 350장씩 영상을 5FPS로 잘라서 이미지로 준다고 했습니다. 
메인화면의 README를 보니 `test_data` 라는 폴더안에 모든 이미지가 다 있는것 같은데 그렇다면 350개마다 새로운 영상의 이미지가 나오는게 맞습니까?

**Comment by nsml-admin** [comment]
테스트셋은 submit할때만 접근할수 있고, `infer`함수로 들어오는 root_path에 있습니다. [참고](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L149)

baseline의 _infer()함수에서 실제로 test_data에 어떻게 접근하는지 참고하시면 도움이 될거같습니다. https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L56-L75

`os.path.join('/home/data/iitp_2020_fallen_final/nsml_dataset/test/test_data')` 이경로는 테스트셋의 경로가 아닙니다.

**Comment by blackCmd** [comment]
> 테스트셋은 submit할때만 접근할수 있고, `infer`함수로 들어오는 root_path에 있습니다. [참고](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L149)
> 
> baseline의 _infer()함수에서 실제로 test_data에 어떻게 접근하는지 참고하시면 도움이 될거같습니다. https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L56-L75
> 
> `os.path.join('/home/data/iitp_2020_fallen_final/nsml_dataset/test/test_data')` 이경로는 테스트셋의 경로가 아닙니다.


말씀하신 코드의 root_dir로는 테스트셋의 디렉토리가 어떻게 구성돼있는지 알 수가 없습니다. 
main.py에 print 문을 써서 경로라도 보고싶은데 print문에 대한 출력이 nsml에서 나오지 않습니다. 혹시 볼 수 있는 방법을 있을까요?

**Comment by nsml-admin** [comment]
https://github.com/AI-GrandChallenge/round-1/tree/master/iitp_falling 에 있는 readme.md 를 보시면 데이터셋에 대한 구성이 있습니다.

submit할때 -t옵션을 줘서 실행하면 새로운 세션이 생성되고 그 세션에 `nsml logs [session]` 을 입력하면 print문에 대한 출력문이 보입니다

**Comment by hi-one-gg** [comment]
> https://github.com/AI-GrandChallenge/round-1/tree/master/iitp_falling 에 있는 readme.md 를 보시면 데이터셋에 대한 구성이 있습니다.
> 
> submit할때 -t옵션을 줘서 실행하면 새로운 세션이 생성되고 그 세션에 `nsml logs [session]` 을 입력하면 print문에 대한 출력문이 보입니다

감사합니다.
