### ISSUE TITLE
[Track4] 평가 Metric 공식을 알려주세요

### ISSUE THREAD

**Issue by JeiKeiLim** [AI-GrandChallenge/round-1#7]
Gemetric F1 Mean Score 라는 방식이 찾아도 많이 안나오네요.
우선 용어로만 보면 모호해서 보통 이런 대회에서는 공식을 주는데 여기서도 공식을 주셨으면 합니다.
아래 셋 중 어떤 것인가요?

01. <img src="https://render.githubusercontent.com/render/math?math=\sqrt{\prod_{c=1...41}{\sqrt{p_c\cdot r_c}}}">

02. <img src="https://render.githubusercontent.com/render/math?math=\sqrt{\prod_{c=1...41}{\frac { 2\cdot (p_c*r_c)  }{ p_c+r_c } }}">

03. <img src="https://render.githubusercontent.com/render/math?math=\frac{1}{41}\sum_{c=1...41}{\sqrt{p_c\cdot r_c}}">

**Comment by ClovaAIAdmin** [comment]
@JeiKeiLim 
네 2번 입니다. 각 클래스 F1 score들을 곱하고 루트를 합니다.

**Comment by JeiKeiLim** [comment]
네 감사합니다.

<img src="https://render.githubusercontent.com/render/math?math=\sqrt{\prod_{c=1...41}{\frac { 2\cdot (p_c*r_c)  }{ p_c+r_c } }}">

이걸로 최종 확정하고 close 하겠습니다.
