### ISSUE TITLE
nsml submit error 관련

### ISSUE THREAD

**Issue by G-Bong** [AI-GrandChallenge/round-1#71]
안녕하세요.
![image](https://user-images.githubusercontent.com/21220998/88650379-a1ed1e00-d103-11ea-9f42-0eb6cacd6729.png)

tack1 submit 시 위와 같은 에러가 발생하고 있습니다.
에러가 난 이후에 session은 종료가 안되고 있는데요,
정상적으로 inference 중인가요? 문제가 없는건지 답변 부탁드립니다.

**Comment by JuYong-Shin** [comment]
submit이 이상하여 질문했는데, 질문이 없어졌네요? 답변 부탁드립니다.
(1) 제가 submit 한 것이 정상적으로 작동했는지 확인할 수 없나요?
제가 submit  한 후 점수가 나왔었는데, 잠시 후에 기록이 없어졌습니다. 전혀 바꾸지 않고 다시 submit 했는데, 점수가 바뀌어서 다시 ranking에 떴습니다. 제가 submit 하는 것이 정상적으로 작동하는지 확인하고 싶습니다.

**Comment by bluebrush** [comment]
@JuYong-Shin 님, https://github.com/AI-GrandChallenge/round-1/issues/64 참고하시어, private 모드로 submit 이력 확인가능합니다.

**Comment by KOR-PAIR** [comment]
@bluebrush 님 
private 모드로 확인해보니 아무런 이력이 없습니다.

NSML Log start!
Usage: nsml logs [OPTIONS] SESSION

Error: Invalid value for "SESSION": Cannot logs [t0023/tr-3/140] (Only nsml rm is valid for submit sessions)

**Comment by G-Bong** [comment]
@bluebrush nsml submit 명령어 사용 시 자동으로 log option을 사용 하는 것 같습니다.
해결 가능할까요?

**Comment by bluebrush** [comment]
@KOR-PAIR님

> @bluebrush 님
> private 모드로 확인해보니 아무런 이력이 없습니다.
> 
> NSML Log start!
> Usage: nsml logs [OPTIONS] SESSION
> 
> Error: Invalid value for "SESSION": Cannot logs [t0023/tr-3/140] (Only nsml rm is valid for submit sessions)

private이력이 확인되지 않는다면 정상 submit 완료된 것이 없는 것 같습니다 .
CLI에서 "nsml submit [sessionID] [model-id]"로 명령하신 후 긴 시간동안 터미널이 가만히 있으며, 이상태 유지되어야합니다. 
nsml 명령을 내리는 시점부터의 터미널 출력은 모두 첨부해주시면 확인이 좀더 쉬울것 같습니다. 

그리고, 웹화면에서는 submit과 관련된 세션은 위와 같이 표시됩니다.

**Comment by bluebrush** [comment]
@G-Bong 님, nsml submit과 함께 사용하신 sessionID확인가능할까요? 그리고, 위의 웹화면은 submit세션에 대한 접근이 안되어 나오는 화면으로 보입니다. 웹화면에서 submit 세션에 대한 확인을 안되며, CLI에서만 결과를 보실 수 있습니다. 또한 submit 과정동안 CLI가 멈춰있는 것럼 보일수 있습니다.

**Comment by G-Bong** [comment]
@bluebrush 네 CLI에서는 멈춰보이고 있습니다. 말씀하신 내용에 의하면 CLI가 멈춰있는 상태가 정상적으로 돌아가는 상태이며, 끝날때까지 놔두라는 말씀이실까요?? SUBMIT 상태에서는 웹에 새롭게 생성되어 있는 submit mode의 session에서 보이는 오류는 신경쓰지 않아도 되는건지 궁금합니다.

**Comment by bluebrush** [comment]
@G-Bong  네에, 실행하신 명령어줄 복사해서 붙여주시면 좀더 확인 가능할 것 같습니다.

**Comment by G-Bong** [comment]
@bluebrush 
![image](https://user-images.githubusercontent.com/21220998/88665765-1e8af700-d11a-11ea-8473-d432222e5aa5.png)
위와 같이 명령어 사용한 후 이 상태로 멈춰있습니다.

**Comment by bluebrush** [comment]
@G-Bong 님, 위 상태는 정상 상황입니다. 최대 60분까지 가만히 있을수 있습니다. 
일단, 알려주신 session으로 submit이 진행될 경우, 아래와 같이 진행되는 것을 확인하였습니다. 
총 19분59초가 소요되며, score는 0.0으로 확인되는 문구가 출력됩니다 
```
ykkim@AL01511999 % time ../nsml submit nsmlteam/tr-1/19 model 
.......
Building docker image. It may take a while
.........load nsml model takes 0.5160107612609863 seconds
.Infer test set. The inference should be completed within 3600 seconds.
.Infer test set takes 1178.9548037052155 seconds
...
Score: 0.0
Done
../nsml submit nsmlteam/tr-1/19 model  0.03s user 0.04s system 0% cpu 19:59.04 total
```
