### ISSUE TITLE
submit 시, Internal server error 발생

### ISSUE THREAD

**Issue by JeiKeiLim** [AI-GrandChallenge/round-1#72]
# 1. Log
```
.......
Building docker image. It may take a while
.........load nsml model takes 0.19525837898254395 seconds
.Infer test set. The inference should be completed within 3600 seconds.
.Error occurred while inference. You can check error 'nsml submit --test'


Infer test set takes 4.251225233078003 seconds
..Error: Fail to get prediction result: t0133/tr-4/186/best
FATA[2020/07/28 19:10:29.977] Internal server error                     
```

# 2. test submit 시 로그
```
.......
Building docker image. It may take a while
...........load nsml model takes 0.19287967681884766 seconds

Session t0133/tr-4/188 is started
.Infer test set. The inference should be completed within 3600 seconds.
.Infer test set takes 2.405902624130249 seconds
.%                                                                                        
```

테스트 submit 시 잘 되지만 일반 submit 을 하면 에러가 나면서 안되네요.
무슨 문제인지 log 도 전혀 나오지 않아 알수가 없습니다.

local 에서 nsml.infer 호출을 통해 테스트를 해봐도 잘 되더군요.
nsml 문제인지 확인부탁드리겠습니다.

**Comment by bluebrush** [comment]
@JeiKeiLim 님, 아래와 오류코드가 반환된 것으로 보입니다.  확인 가능하실까요?

  File "/app/nsml_utils.py", line 59, in infer
    return inference(model, data_path)
  File "/app/utils.py", line 59, in inference
    logit = model.predict(test_set)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 618, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  ValueError: `generator` yielded an element of shape (48, 64, 4) where an element of shape (48, 64, 3) was expected.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 826, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape (48, 64, 4) where an element of shape (48, 64, 3) was expected.

```
	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_predict_function_6287]
```

**Comment by JeiKeiLim** [comment]
> @JeiKeiLim 님, 아래와 오류코드가 반환된 것으로 보입니다. 확인 가능하실까요?
> 
> File "/app/nsml_utils.py", line 59, in infer
> return inference(model, data_path)
> File "/app/utils.py", line 59, in inference
> logit = model.predict(test_set)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
> return method(self, *args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
> tmp_batch_outputs = predict_function(iterator)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in **call**
> result = self._call(*args, **kwds)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 618, in _call
> results = self._stateful_fn(*args, **kwds)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in **call**
> return graph_function._filtered_call(args, kwargs) # pylint: disable=protected-access
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
> self.captured_inputs)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
> ctx, args, cancellation_manager=cancellation_manager))
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
> ctx=ctx)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
> inputs, attrs, num_outputs)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: `generator` yielded an element of shape (48, 64, 4) where an element of shape (48, 64, 3) was expected.
> Traceback (most recent call last):
> 
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in **call**
> ret = func(*args)
> 
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
> return func(*args, **kwargs)
> 
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 826, in generator_py_func
> "of shape %s was expected." % (ret_array.shape, expected_shape))
> 
> ValueError: `generator` yielded an element of shape (48, 64, 4) where an element of shape (48, 64, 3) was expected.
> 
> ```
> 	 [[{{node PyFunc}}]]
> 	 [[IteratorGetNext]] [Op:__inference_predict_function_6287]
> ```

아 네 확인했습니다. 입력 이미지가 rgba 인줄은 몰랐네요.
close 하겠습니다!
