### ISSUE TITLE
submit 이 완료된 세션의 삭제

### ISSUE THREAD

**Issue by NeuroAI-lab** [AI-GrandChallenge/round-1#85]
submit이 완료된 세션이 삭제되지않고 약 10시간동안 Running상태가 되어 있습니다.
세션이름은  t0117/tr-2/110으로  이전 issue에서 

`nsml rf -f [sessionID]`

을 통해 삭제가 가능하다 하여 시도하였으나 명령어가 존재하지않아 실행이 되지않습니다.

```
nsml stop
nsml rm 
```
또한 적용이 되지않습니다.

다른 해결방안이 있나요?

**Comment by minyoung62** [comment]
nsml rm -f [sessionID] 입니다.

**Comment by NeuroAI-lab** [comment]
해결 완료하였습니다. 답변 감사합니다!!
