### ISSUE TITLE
최종 결과 파일은 어떤 경로에 제출해야합니까?

### ISSUE THREAD

**Issue by hi-one-gg** [AI-GrandChallenge/round-1#86]
트랙 1에 참가하는 기업입니다,

또한 결과파일을 제출하고 싶은데 결과파일을 어디 경로에 제출해야합니까? 
결과제출용 코드를 따로 제공해주면 참 좋을거같은데 샘플코드를 보며 수정해야하니 너무 번거롭네요 ㅠㅠ
제공해주실순 없습니까? 기술을 다 만들어놨는데 제대로 제출 한번 못해보고있습니다.

**Comment by nsml-admin** [comment]
안녕하세요.
https://github.com/AI-GrandChallenge/round-1/tree/master/iitp_falling 여기에 있는 readme에 `Local model 로드` 부분에 적어두긴 했는데요,

현재는 세션상에 모델을 저장까지 한 상태인것같습니다.

최종적으로는 `nsml submit [session]`을 이용해서 리더보드에 결과를 제출해야합니다.

load함수는 [여기](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L193)에서 nsml이 자동으로 실행하게 됩니다.

그후에 infer함수가 [실행](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L149)되게 됩니다. 


infer함수에서 return된 값을 자동으로 nsml상에서 파싱하고 저장한다음 evaluate과정을 거친후에 문제가 없으면 최종적으로 리더보드에 올라가게 됩니다.

감사합니다.

**Comment by hi-one-gg** [comment]
> 안녕하세요.
> https://github.com/AI-GrandChallenge/round-1/tree/master/iitp_falling 여기에 있는 readme에 `Local model 로드` 부분에 적어두긴 했는데요,
> 
> 현재는 세션상에 모델을 저장까지 한 상태인것같습니다.
> 
> 최종적으로는 `nsml submit [session]`을 이용해서 리더보드에 결과를 제출해야합니다.
> 
> load함수는 [여기](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L193)에서 nsml이 자동으로 실행하게 됩니다.
> 
> 그후에 infer함수가 [실행](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_falling/main.py#L149)되게 됩니다.
> 
> infer함수에서 return된 값을 자동으로 nsml상에서 파싱하고 저장한다음 evaluate과정을 거친후에 문제가 없으면 최종적으로 리더보드에 올라가게 됩니다.
> 
> 감사합니다.

매번 도와주시니 감사합니다
