### ISSUE TITLE
[Track-1] 문제정의서 문의

### ISSUE THREAD

**Issue by bjo9280** [AI-GrandChallenge/round-1#87]
안녕하세요 문제정의서 궁금한점 문의드려요

최종세부문제정의서에 csv출력 기준을 보면 프레임당 하나만 출력하라고 되어있는데 
csv파일 작성예시를 보면  같은 프레임에 박스가 두개가 출력되있는걸로 보여서 문의드립니다. 아래는 해당내용입니다. 
[[x1y2x1y2],[x1y1x2y2]] 이런식으로 박스두개를 제출 하지 말라는걸로 이해하고 csv파일 작성예시 처럼 제출하면 되는건가요??

바운딩 박스 csv출력 기준
 1. 바운딩 박스는 프레임당 하나만 csv로 출력*하되, 다수 인원의 실신상황인
    경우 GT는 모든 인원에 대해 바운딩 박스가 쳐져 있음**
   (하나의 프레임에 복수의 바운딩 박스가 기록하는 모델의 경우 해당 팀은 실격처리 예정)
  (이중 하나의 대상만 맞춰도 올바른 답으로 인정)

< csv파일 작성예시 >

|file_name|x1y1x2y2|
|------|---|
|t1_cam1_0033.jpg |10 20 70 120|
|t1_cam1_0033.jpg |90 100 260 230|

**Comment by sangdooyun** [comment]
@bjo9280 바운딩 박스는 file_name 하나당 하나만 출력해야 합니다. 복수의 gt가 존재하는 경우 그 중 하나만 맞춰도 맞는 것으로 간주하기 때문입니다. csv 파일 작성 예시는 잘못된 것으로 보입니다.
