### ISSUE TITLE
[track3]data_loader 관련 질문 있습니다.

### ISSUE THREAD

**Issue by minyoung62** [AI-GrandChallenge/round-1#88]
track3 data_local_loader를 수정하고 nsml클라우드에 올린 후 submit을 하게되면 수정된 data_local_loader를 이용하여 infer 하게 되는 건지 궁금합니다.

**Comment by nsml-admin** [comment]
안녕하세요.

`data_local_loader.py` 나 `data_loader.py` 를 수정한다고해도 submit 시에는 반영되지않습니다.

**Comment by minyoung62** [comment]
@nsml-admin data_loader.py를 보면 데이터가 224, 224로 resize를 하는데 submit할 때 데이터도 224, 224로 infer 하는 건가요?
아니면 별도의 test_loader를 따로 구현해도 되나요?

**Comment by nsml-admin** [comment]
data_loader.py 부분은 NSML에서 실행되고, baseline 만든분들이 올린 data_loader.py가 호출됩니다. (예제에 올라간 data_loader.py랑 똑같음)

예제에 나와있는 data_loader.py는 infer에서 return된 값들이 어떤식으로 파싱되고 저장되는지 보여주기 위함이라서 신경을 안쓰셔도 될거같습니다.

중요한건  infer에서 리턴되는 포맷들이 baseline설계자 분들이 기대한 포맷과 똑같아야 합니다.

track3같은경우는 [여기](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_trash/main.py#L54-L56)랑 똑같은 포맷으로 return하시면 될것같습니다.

**Comment by StoneGlove** [comment]
@nsml-admin 안녕하세요 4번트랙 진행중인데요. tensorflow2 기반으로 모든 구현을 하고 있었기 때문에 data_loader.py 를 TF2버젼으로 새로 작성했습니다. 말씀하신바에 따르면 data_loader.py 는 baseline 만드신 분들이 만드신 파일을 쓰게 되므로 저의 TF2와는 호환이 안될것 같습니다. 결론적으로, 본 과제는 torch 로만 해야 하는 과제가 되는건가요?

**Comment by nsml-admin** [comment]
@StoneGlove track 4의 data loader를 보면 https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_category/reference/data_loader.py tf2와 호환이 안될만한 부분이 없습니다.

아마 https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_category/data_loader.py 이거랑 헷갈리신거 같은데요,

저부분은 infer함수에서 호출되는것이라서 크게 상관없을걸로 보입니다.

결과적으로 nsml에서 사용하는 data_loader.py는 https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_category/reference/data_loader.py 이것을 사용하게 될것이고, [infer 함수](https://github.com/AI-GrandChallenge/round-1/blob/master/iitp_category/nsml_utils.py#L20-L21) 에서 반환하는 format만 맞춰주시면 됩니다.
