### ISSUE TITLE
[트랙3] data loader CustomDataset 문의

### ISSUE THREAD

**Issue by withcat-net** [AI-GrandChallenge/round-1#92]
트랙3 예제 코드 중 data_local_loader.py 안에 CustomDataset 클래스의 경우 이 클래스를 바꾸지 말라는 주석이 달려있습니다.
저희 모델의 경우 Dataset 클래스도 커스터마이징해서 이미 학습시켰는데, 데이터셋 클래스 부분을 임의로 수정하면 안되나요?

**Comment by junsukchoe** [comment]
안녕하세요.

말씀하신 부분 수정 가능합니다! 해당 부분 주석 수정되었습니다:https://github.com/AI-GrandChallenge/round-1/blob/34d8b44f3562b62a3be67ad4f481a59da0af9d6f/iitp_trash/data_local_loader.py#L28

**Comment by withcat-net** [comment]
submit 할 때는 data_local_loader 부분이 적용이 안되는 걸로 알고 있는데,
Dataset 클래스를 커스터마이징해서 썼을 경우에 submit 할 때도 적용되나요?

**Comment by junsukchoe** [comment]
`nsml submit [a_session]` 에서 `a_session`에 저장되어 있는 파일들을 복사하여 사용하기 때문에 `data_local_loader.py`를 수정하신 부분은 반영됩니다. 단, `data_loader.py`와 `evaluation.py`는 수정하셔도 submit 시 반영되지 않습니다.

**Comment by withcat-net** [comment]
감사합니다.
