### ISSUE TITLE
[track-2] librosa 라이브러리 "OSError: sndfile library not found"

### ISSUE THREAD

**Issue by symoon94** [AI-GrandChallenge/round-1#93]
안녕하세요. teamID 0048입니다.

세션: t0048/tr-2/84

librosa 라이브러리 환경 구축 중 어려움이 있어 이슈 올립니다.
import librosa시 "OSError: sndfile library not found" 같은 메시지가 나옵니다.

[#31](https://github.com/Naver-AI-Hackathon/AI-Speech/issues/31#issuecomment-533498010) 참고하여 이슈를 해결해보려 했으나 잘 안돼 여쭤봅니다.

아래는 작성한 setup.py
```
#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch1.0keras2.2
from distutils.core import setup
import setuptools

setup(
    name="grand",
    version='1.0',
    install_requires=[
        'librosa',
        'python-Levenshtein'
    ]   
)
```

아래는 작성한 requirements.txt
```
#nsml: nsml/ml:cuda9.0-cudnn7-tf-1.11torch1.0keras2.2
openpyxl
adamp
numpy
pandas
scikit-learn
Keras==2.3.1
tensorflow-gpu==2.1.0
numba==0.43.0
llvmlite==0.32.1
opencv-python
matplotlib
```

**Comment by nsml-admin** [comment]
안녕하세요. 
참조해주신 링크에서 해결한 방법대로 해보니깐 `OSError: sndfile library not found` 에러는 넘어갔습니다.

main.py와 같은 위치에 `nsml_package.txt` 파일을 만들고 그안에 `libsndfile1` 를 적으면 됩니다.
